---
name: ci
on:
  push:
    paths:
      - "!*.md"
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: build and push to dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: daixijun1990/kubectl
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
      - name: build and push to github package
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/daixijun/kubectl-docker/kubectl
          username: ${{ secrets.github_username }}
          password: ${{ secrets.github_password }}
          registry: docker.pkg.github.com
